import type {Metadata} from "next";
import "./globals.css";
import {inter} from "@/configs/fonts";
import {ThemeProvider} from "@/providers/theme/ThemeProvider";
import {FC, PropsWithChildren} from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({
                                               children,
                                           }) => {
    return (
        <html lang="en">
        <body
            className={inter.className}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}

export default RootLayout;
